spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&charactEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.hwua.storesystem.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    interceptors:
logging:
  level:
    com.hwua.storesystem: debug
#  file: D:\logs\hello.log
server:
  port: 8888
